name: Publish Release

# Build is too complicated for this to work right now!

on:
  push:
    # tags:
    #   - '*.*.*'

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Setup LLVM 19
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19"
      - name: Install xmake
        shell: pwsh
        run: |
          pip install xmake
      - name: Clone CommonLibSF
        shell: pwsh
        run: |
          git clone --recurse-submodules https://github.com/libxse/commonlibsf third_party/commonlibsf_build_src
      - name: Build CommonLibSF
        shell: pwsh
        working-directory: third_party/commonlibsf_build_src
        run: |
          xmake f -m releasedbg --toolchain=clang-cl
          xmake build
      - name: Configure AutoStartSFSE
        shell: pwsh
        run: |
          cmake -S . -B build-clangcl -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_C_COMPILER=clang-cl `
            -DCMAKE_CXX_COMPILER=clang-cl `
            -DCOMMONLIBSF_INCLUDE_DIR="${{ github.workspace }}\third_party\commonlibsf_build_src\include" `
            -DCOMMONLIBSF_SHARED_INCLUDE_DIR="${{ github.workspace }}\third_party\commonlibsf_build_src\lib\commonlib-shared\include" `
            -DCOMMONLIBSF_LIBRARY="${{ github.workspace }}\third_party\commonlibsf_build_src\build\windows\x64\releasedbg\commonlibsf.lib" `
            -DCOMMONLIBSF_SHARED_LIBRARY="${{ github.workspace }}\third_party\commonlibsf_build_src\build\windows\x64\releasedbg\commonlib-shared.lib"
      - name: Build AutoStartSFSE
        shell: pwsh
        run: |
          cmake --build build-clangcl --config Release
      - name: Verify exports
        shell: pwsh
        run: |
          llvm-objdump -p build-clangcl/AutoStartSFSE.dll | Select-String "SFSEPlugin_(Load|Preload|Version)"
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build-clangcl/AutoStartSFSE.dll
      - name: Zip files
        run: zip -r auto-start.zip ./build-clangcl/AutoStartSFSE.dll
      - name: Upload mod to NexusMods
        id: upload
        uses: Nexus-Mods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          file_group_id: ${{ vars.NEXUSMODS_FILE_GROUP_ID }}
          filename: mod-manager.zip
          display_name: "Auto Start"
          description: "Continue latest save on game load"
          version: ${{ github.event.release.tag_name || github.event.inputs.version ||  github.ref_name }}
